import fs from 'node:fs/promises';
import {fileURLToPath} from 'node:url';
import {Workbook,SpreadsheetFile} from '@oai/artifact-tool';
const out=new URL('../outputs/atlas-finance-demo/',import.meta.url);
const wb=Workbook.create(),s=wb.worksheets.add('BvA'),log=wb.worksheets.add('Booking log');
s.showGridLines=false;log.showGridLines=false;s.tabColor='#245C4D';
s.getRange('A2').values=[['September 2026 income and outflow budget']];
s.getRange('A3').values=[['Atlas tourism product launch | sample data in CNY. Simulated bookings affect projections, not actual income or expense.']];
s.getRange('A5:F5').values=[['INCOME','Budget','Actual','Simulated pipeline','Projected income','Forecast variance']];
s.getRange('H5:M5').values=[['OUTFLOW','Budget','Actual','Simulated commitment','Projected outflow','Budget remaining']];
s.getRange('A9:F9').values=[['Customer','Budget','Actual','Simulated pipeline','Projected income','Forecast variance']];
s.getRange('H9:M9').values=[['Expense category','Budget','Actual','Simulated commitment','Projected outflow','Budget remaining']];
s.getRange('A10:D13').values=[['Koru Travel',40000,18000,0],['Riverstone Group',55000,22000,0],['Pine Studio',30000,12000,0],['New launch customers',25000,0,0]];
s.getRange('H10:K16').values=[['Flights',45000,18500,0],['Hotels',38000,14000,0],['Guides',12000,3500,0],['Transport',18000,7200,0],['Activities',15000,6100,0],['Marketing',10000,4800,0],['Customer care',7000,2400,0]];
for(let r=10;r<=29;r++){s.getRange('E'+r).formulas=[['=IF(A'+r+'="","",C'+r+'+D'+r+')']];s.getRange('F'+r).formulas=[['=IF(A'+r+'="","",E'+r+'-B'+r+')']];s.getRange('L'+r).formulas=[['=IF(H'+r+'="","",J'+r+'+K'+r+')']];s.getRange('M'+r).formulas=[['=IF(H'+r+'="","",I'+r+'-L'+r+')']];}
s.getRange('A6').values=[['September total']];s.getRange('H6').values=[['September total']];
for(const c of ['B','C','D','E','F','I','J','K','L','M'])s.getRange(c+'6').formulas=[['=SUM('+c+'10:'+c+'29)']];
s.getRange('A7').values=[['Actual margin']];s.getRange('B7').formulas=[['=C6-J6']];
s.getRange('H7').values=[['Projected margin']];s.getRange('I7').formulas=[['=E6-L6']];
s.getRange('A31').values=[['Actual = recorded transactions. Simulated pipeline and commitment = proposed product-launch work only. No booking or payment occurred.']];
s.getRange('A2:M31').format.font={name:'Arial',size:10,color:'#27342F'};
s.getRange('A2').format.font={name:'Arial',size:15,bold:true,color:'#183D33'};
s.getRange('A3').format.font={name:'Arial',size:10,italic:true,color:'#64736A'};
s.getRange('A5:F5').format={fill:'#E8F0EC',font:{name:'Arial',size:10,bold:true,color:'#254D3F'}};
s.getRange('H5:M5').format={fill:'#F2EEE6',font:{name:'Arial',size:10,bold:true,color:'#64533C'}};
s.getRange('A9:F9').format={fill:'#245C4D',font:{name:'Arial',size:10,bold:true,color:'#FFFFFF'}};
s.getRange('H9:M9').format={fill:'#715F46',font:{name:'Arial',size:10,bold:true,color:'#FFFFFF'}};
s.getRange('A6:F7').format.fill='#F7FAF7';s.getRange('H6:M7').format.fill='#FBF8F4';
s.getRange('A6:M7').format.font={name:'Arial',size:10,bold:true,color:'#183D33'};
s.getRange('B10:D29').format.font={name:'Arial',size:10,color:'#2856A5'};
s.getRange('I10:K29').format.font={name:'Arial',size:10,color:'#2856A5'};
s.getRange('B6:F29').setNumberFormat('"CNY "#,##0;("CNY "#,##0);-');
s.getRange('I6:M29').setNumberFormat('"CNY "#,##0;("CNY "#,##0);-');
s.getRange('A:A').format.columnWidth=26;s.getRange('B:F').format.columnWidth=20;s.getRange('G:G').format.columnWidth=3;s.getRange('H:H').format.columnWidth=23;s.getRange('I:M').format.columnWidth=20;
s.getRange('A3:M3').format.rowHeight=28;s.getRange('A31:M31').format.rowHeight=28;s.freezePanes.freezeRows(9);
s.getRange('M10:M29').conditionalFormats.add('cellIs',{operator:'lessThan',formula:0,format:{fill:'#FCECE8',font:{color:'#AE3C2F',bold:true}}});
log.getRange('A2').values=[['Simulated booking commitments']];
log.getRange('A3').values=[['Reviewed updates change projected income and outflow, not Actual. This register is a demonstration, not a general ledger.']];
log.getRange('A5:H5').values=[['Booking ID','Customer','Status','Quote (CNY)','Expense category','Committed (CNY)','Reviewed by','Recorded at']];
log.getRange('A2:H6').format.font={name:'Arial',size:10,color:'#27342F'};
log.getRange('A2').format.font={name:'Arial',size:15,bold:true,color:'#183D33'};
log.getRange('A3').format.font={name:'Arial',size:10,italic:true,color:'#64736A'};
log.getRange('A5:H5').format={fill:'#245C4D',font:{name:'Arial',size:10,bold:true,color:'#FFFFFF'}};
log.getRange('A:A').format.columnWidth=30;log.getRange('B:B').format.columnWidth=28;log.getRange('C:C').format.columnWidth=23;log.getRange('D:F').format.columnWidth=19;log.getRange('G:H').format.columnWidth=24;log.freezePanes.freezeRows(5);
wb.recalculate();
console.log((await wb.inspect({kind:'table',range:'BvA!A5:M16',include:'values,formulas',tableMaxRows:12,tableMaxCols:13,maxChars:8000})).ndjson);
console.log((await wb.inspect({kind:'match',searchTerm:'#REF!|#DIV/0!|#VALUE!|#NAME\\?|#N/A|#NUM!|#NULL!|#SPILL!|#CALC!',options:{useRegex:true,maxResults:50}})).ndjson);
await fs.mkdir(out,{recursive:true});
for(const name of ['BvA','Booking log']){const p=await wb.render({sheetName:name,range:name==='BvA'?'A1:M18':'A1:H8',scale:1.3,format:'png'});await fs.writeFile(new URL(name.toLowerCase().replace(' ','-')+'.png',out),new Uint8Array(await p.arrayBuffer()));}
const file=await SpreadsheetFile.exportXlsx(wb);await file.save(fileURLToPath(new URL('monthly-finance-demo.xlsx',out)));
